name: Scrape IMDb Picks

on:
  schedule:
    - cron: '0 8 * * *' # ogni giorno alle 8:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scraper
        run: python scraper/actions.py

      - name: Commit & Push data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "update data.json"
          git push
