name: Aggiorna Trending Pickflix

on:
  schedule:
    - cron: '0 4 * * *'  # Esegui ogni giorno alle 04:00 UTC
  workflow_dispatch:      # Permette anche avvio manuale dal pannello Actions

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo scraper
        run: python scraper/actions.py

      - name: Commit e push di data.json aggiornato
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Aggiornamento automatico alle 04:00 UTC" || echo "Nessuna modifica"
          git push
